"""Train the digit classifier from vectors produced by tools/extract.mjs and
write digit-model.js (int8-quantised weights, ~40KB).

usage: python3 tools/train.py OUT_JS PREFIX [PREFIX...]
"""
import base64, json, sys
import numpy as np

N = 20
HID = 96
CLASSES = 10  # digits 1-9 + "not a digit"


def load(prefixes):
    xs, ys = [], []
    for p in prefixes:
        y = np.fromfile(p + '.y.u8', np.uint8)
        x = np.fromfile(p + '.x.f32', np.float32).reshape(len(y), N * N)
        xs.append(x); ys.append(y)
    return np.concatenate(xs), np.concatenate(ys)


def shift(x, rng):
    img = x.reshape(-1, N, N)
    out = np.zeros_like(img)
    for i in range(len(img)):
        dx, dy = rng.integers(-1, 2, 2)
        out[i] = np.roll(np.roll(img[i], dy, 0), dx, 1)
    return out.reshape(-1, N * N)


def main():
    out_js, prefixes = sys.argv[1], sys.argv[2:]
    X, Y = load(prefixes)
    print('samples', len(Y), 'per class', np.bincount(Y, minlength=CLASSES))
    rng = np.random.default_rng(0)
    idx = rng.permutation(len(Y))
    X, Y = X[idx], Y[idx]
    nval = len(Y) // 20
    Xv, Yv, X, Y = X[:nval], Y[:nval], X[nval:], Y[nval:]
    cw = len(Y) / (CLASSES * np.maximum(np.bincount(Y, minlength=CLASSES), 1))
    cw = np.minimum(cw, 5).astype(np.float32)

    W1 = (rng.standard_normal((HID, N * N)) * np.sqrt(2 / (N * N))).astype(np.float32)
    b1 = np.zeros(HID, np.float32)
    W2 = (rng.standard_normal((CLASSES, HID)) * np.sqrt(2 / HID)).astype(np.float32)
    b2 = np.zeros(CLASSES, np.float32)
    params = [W1, b1, W2, b2]
    m = [np.zeros_like(p) for p in params]
    v = [np.zeros_like(p) for p in params]
    lr, B1, B2, t = 2e-3, 0.9, 0.999, 0

    def forward(x):
        h = np.maximum(0, x @ W1.T + b1)
        o = h @ W2.T + b2
        o -= o.max(1, keepdims=True)
        p = np.exp(o); p /= p.sum(1, keepdims=True)
        return h, p

    for epoch in range(20):
        perm = rng.permutation(len(Y))
        for s in range(0, len(Y), 256):
            bi = perm[s:s + 256]
            x = shift(X[bi], rng) if epoch < 17 else X[bi]
            y = Y[bi]
            h, p = forward(x)
            g = p.copy(); g[np.arange(len(y)), y] -= 1
            g *= cw[y][:, None] / len(y)
            gW2 = g.T @ h + 1e-4 * W2; gb2 = g.sum(0)
            gh = (g @ W2) * (h > 0)
            gW1 = gh.T @ x + 1e-4 * W1; gb1 = gh.sum(0)
            t += 1
            for i, (pp, gg) in enumerate(zip(params, [gW1, gb1, gW2, gb2])):
                m[i] = B1 * m[i] + (1 - B1) * gg
                v[i] = B2 * v[i] + (1 - B2) * gg * gg
                pp -= lr * (m[i] / (1 - B1 ** t)) / (np.sqrt(v[i] / (1 - B2 ** t)) + 1e-8)
        if epoch == 12: lr /= 4
        _, pv = forward(Xv)
        acc = (pv.argmax(1) == Yv).mean()
        print(f'epoch {epoch} val acc {acc * 100:.2f}%')

    _, pv = forward(Xv)
    pred = pv.argmax(1)
    conf = np.zeros((CLASSES, CLASSES), int)
    for a, b in zip(Yv, pred): conf[a, b] += 1
    print(conf)

    def q(w):
        scale = float(np.abs(w).max() / 127)
        return base64.b64encode(np.round(w / scale).astype(np.int8).tobytes()).decode(), scale

    layers = []
    for W, b in [(W1, b1), (W2, b2)]:
        w64, scale = q(W)
        layers.append({'inp': W.shape[1], 'out': W.shape[0], 'scale': scale,
                       'b': [round(float(x), 5) for x in b], 'w': w64})
    with open(out_js, 'w') as f:
        f.write('// Generated by tools/train.py - digit classifier weights (int8)\n')
        f.write('export default ' + json.dumps({'layers': layers}) + ';\n')


if __name__ == '__main__':
    main()
